# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=400)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
