# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='task_text',
        ),
    ]
