# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20170306_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-time_created']},
        ),
    ]
