# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_remove_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='archived',
        ),
    ]
